/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_okno;

import gui_hlavni.HlavniJFrame;
import gui.Pozemky;
import gui.Stavby;
import gui_okno.Vloz_vlastnika;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import logika.Vlastnik;

/**
 *
 * @author strmiska
 */
public class Vlastnictvi extends javax.swing.JDialog {
    public gui.Pozemky parentPozemky;
    public gui.Stavby parentStavby;
 //   private gui.Stavby parent2;
    public int objectPK;
    public int officerPK;
    public static Vloz_vlastnika vlastnik;
    public int indexVlastnika = -1;
    public int zbyvajiciPodil = 100;
    public DefaultListModel<String> listVlastniku = new DefaultListModel<>();
    public String zacatekVlastnictvi ="";
    Vlastnik vlastnikSPodilem = new Vlastnik();
    /**
     * Creates new form Vlastnictvi
     */
    public Vlastnictvi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public void initForInsertPozemky(Pozemky parent, int idObjektu)
	{
              this.parentPozemky = parent;
              inicializuj(idObjektu);              
        }
   
    public void initForInsertStavby(Stavby parent, int idObjektu)
	{
              this.parentStavby = parent;
              inicializuj(idObjektu);              
        }
    public void inicializuj(int idObjektu){
            objectPK = idObjektu;
              label_id.setText(objectPK+"");              
              naplnUdaje();
    }
    
    public void naplnUdaje(){
        zbyvajiciPodil = 100;
        listVlastniku.clear();
        String sql = "select KAT_PERSONS.PERSON_PK, KAT_persons.name,  KAT_persons.Surname,Kat_ownership.property_share, KAT_OFFICERS.OFFICER_PK, \n" +
"(select Kat_persons.name FROM KAT_PERSONS, KAT_OFFICERS WHERE KAT_PERSONS.PERSON_PK = KAT_OFFICERS.OFFICER_PK and KAT_OWNERSHIP.OFFICER_FK = KAT_OFFICERS.OFFICER_PK)UrednikName, \n" +
"(select Kat_persons.SURNAME FROM KAT_PERSONS, KAT_OFFICERS WHERE KAT_PERSONS.PERSON_PK = KAT_OFFICERS.OFFICER_PK and KAT_OWNERSHIP.OFFICER_FK = KAT_OFFICERS.OFFICER_PK)UrednikPrijmeni\n" +
", Kat_ownership.VFROM FROM KAT_MAP_OBJECTS\n" +
"INNER JOIN KAT_OWNERSHIP ON KAT_MAP_OBJECTS.object_pk = KAT_OWNERSHIP.OBJECT_FK\n" +
"INNER JOIN KAT_PERSONS ON KAT_OWNERSHIP.PERSON_FK = KAT_PERSONS.PERSON_PK\n" +
"INNER JOIN KAT_OFFICERS ON KAT_OWNERSHIP.OFFICER_FK = KAT_OFFICERS.OFFICER_PK\n" +
"WHERE OBJECT_PK = ?";

     try(PreparedStatement pstmt = HlavniJFrame.dtb.getConnection().prepareStatement(sql)){ 
         pstmt.setInt(1, objectPK);
         ResultSet rs = pstmt.executeQuery();
         if (!rs.isBeforeFirst() ) {    
                label_urednik.setText("Neschváleno");
//                Btn_prejdiNaOsobu.setEnabled(false);
//                Btn_prejdiNaUrednika.setEnabled(false);
 
            } else{
//                Btn_prejdiNaOsobu.setEnabled(true);
//                Btn_prejdiNaUrednika.setEnabled(true);
//                
            }
            while (rs.next()) {

                    float vlastnenyPodil = rs.getFloat(4)*100;    
                    zacatekVlastnictvi = rs.getString(8);
                    officerPK = rs.getInt(5);
                    label_zacatekVlastnictvi.setText(logika.Datum.zmenaNaString(rs.getString(8)));
                    label_urednik.setText(rs.getString(6) + " " + rs.getString(7));
                    listVlastniku.addElement(rs.getString(2) +" "+ rs.getString(3) + " " + vlastnenyPodil + "%");
                    zbyvajiciPodil -= vlastnenyPodil;
             }
     }
    catch (SQLException sqlEx) {
        System.err.println("SQLException: " + sqlEx.getMessage());
    }
     indexVlastnika = 0;
     vlastnikSPodilem.personPK = logika.Dotazy.zjistiPKVlastnika(objectPK, indexVlastnika);
     List_seznamVlastniku.setModel(listVlastniku);
     
     if(zbyvajiciPodil != 0){
         Btn_novyVlastnik.setEnabled(true);
     }else{
        Btn_novyVlastnik.setEnabled(false);
     }
     
    }
    
    public void vymazVlastnika(){
        String sql = "DELETE FROM KAT_OWNERSHIP WHERE PERSON_FK = ? AND OBJECT_FK = ?";
    try(PreparedStatement pstmt = HlavniJFrame.dtb.getConnection().prepareStatement(sql)){
        pstmt.setInt(1, vlastnikSPodilem.personPK);
        pstmt.setInt(2, objectPK);
        
        pstmt.executeUpdate();
    }catch(SQLException SQLEx){
        System.err.println("SQLxception: " + SQLEx.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        label_urednik = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        List_seznamVlastniku = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        label_zacatekVlastnictvi = new javax.swing.JLabel();
        Btn_OdstanitVlastnika = new javax.swing.JButton();
        Btn_UpravitPodil = new javax.swing.JButton();
        Btn_novyVlastnik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Vlastnitví nemovitosti id:");

        label_id.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_id.setText("id");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Úředník:");

        label_urednik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_urednik.setText("jméno + příjmení");

        List_seznamVlastniku.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                List_seznamVlastnikuValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(List_seznamVlastniku);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Seznam vlastníků:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Začátek vlastnictví:");

        label_zacatekVlastnictvi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_zacatekVlastnictvi.setText("02.02.2002");

        Btn_OdstanitVlastnika.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_OdstanitVlastnika.setText("Odstranit Vlastníka");
        Btn_OdstanitVlastnika.setEnabled(false);
        Btn_OdstanitVlastnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_OdstanitVlastnikaActionPerformed(evt);
            }
        });

        Btn_UpravitPodil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_UpravitPodil.setText("Upravit Podíl");
        Btn_UpravitPodil.setEnabled(false);
        Btn_UpravitPodil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UpravitPodilActionPerformed(evt);
            }
        });

        Btn_novyVlastnik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_novyVlastnik.setText("Přidat nového vlastníka");
        Btn_novyVlastnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_novyVlastnikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(label_urednik))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(label_zacatekVlastnictvi))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Btn_novyVlastnik)
                        .addGap(37, 37, 37)
                        .addComponent(Btn_UpravitPodil)
                        .addGap(36, 36, 36)
                        .addComponent(Btn_OdstanitVlastnika)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(label_id))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(label_zacatekVlastnictvi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(label_urednik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_UpravitPodil)
                    .addComponent(Btn_novyVlastnik)
                    .addComponent(Btn_OdstanitVlastnika))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void List_seznamVlastnikuValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_List_seznamVlastnikuValueChanged
        indexVlastnika = List_seznamVlastniku.getSelectedIndex() ;
        
        vlastnikSPodilem = logika.Dotazy.zjistiUdajeVlastnika(objectPK, indexVlastnika);
        Btn_UpravitPodil.setEnabled(true);
        Btn_OdstanitVlastnika.setEnabled(true);
        vlastnikSPodilem.personPK = vlastnikSPodilem.personPK;
        vlastnikSPodilem.podil = vlastnikSPodilem.podil;

    }//GEN-LAST:event_List_seznamVlastnikuValueChanged

    private void Btn_OdstanitVlastnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_OdstanitVlastnikaActionPerformed
        vymazVlastnika();
        naplnUdaje();
        if(parentPozemky != null){                
            parentPozemky.zobrazPozemek();
        }
        if(parentStavby != null){                
            parentStavby.zobrazStavbu();
        }
    }//GEN-LAST:event_Btn_OdstanitVlastnikaActionPerformed

    private void Btn_UpravitPodilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UpravitPodilActionPerformed
          vlastnik = new Vloz_vlastnika(HlavniJFrame.hlavniOkno, true);
   //       zbyvajiciPodil += vlastnikSPodilem.podil;
          vlastnik.initForInsert(this, objectPK, true);
   //       HlavniJFrame.urednik.initForInsert(this, false, HlavniJFrame.hlavniOkno.vsechnyOsoby);
          vlastnik.setVisible(true);
    }//GEN-LAST:event_Btn_UpravitPodilActionPerformed

    private void Btn_novyVlastnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_novyVlastnikActionPerformed
          vlastnik = new Vloz_vlastnika(HlavniJFrame.hlavniOkno, true);
          vlastnik.initForInsert(this, objectPK, false);
   //       HlavniJFrame.urednik.initForInsert(this, false, HlavniJFrame.hlavniOkno.vsechnyOsoby);
          vlastnik.setVisible(true);
    }//GEN-LAST:event_Btn_novyVlastnikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vlastnictvi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vlastnictvi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vlastnictvi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vlastnictvi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Vlastnictvi dialog = new Vlastnictvi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_OdstanitVlastnika;
    private javax.swing.JButton Btn_UpravitPodil;
    private javax.swing.JButton Btn_novyVlastnik;
    private javax.swing.JList<String> List_seznamVlastniku;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_urednik;
    private javax.swing.JLabel label_zacatekVlastnictvi;
    // End of variables declaration//GEN-END:variables
}
