/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author strmiska
 */
public class Osoby extends javax.swing.JPanel {

    /**
     * Creates new form Osoby
     */
    public Osoby() {
        initComponents();
        
    }
    
    public void zobrazOkno(int index){
       jTabbedPane2.setSelectedIndex(index);
    }
    
    public VsechnyOsoby getVsechnyOsoby(){
         return vsechnyOsoby;
    }
    public Urednici getUrednici(){
         return urednici;
    }
    public Vlastnici getVlastnici(){
         return vlastnici;
    }
    public void inicializuj(){
        vsechnyOsoby.inicializuj();
        urednici.inicializuj();
        vlastnici.inicializuj();
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        vsechnyOsoby = new gui.VsechnyOsoby();
        urednici = new gui.Urednici();
        vlastnici = new gui.Vlastnici();

        jTabbedPane2.addTab("Všechny osoby", vsechnyOsoby);
        jTabbedPane2.addTab("Úředníci", urednici);
        jTabbedPane2.addTab("Vlastníci", vlastnici);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane2;
    private gui.Urednici urednici;
    private gui.Vlastnici vlastnici;
    private gui.VsechnyOsoby vsechnyOsoby;
    // End of variables declaration//GEN-END:variables
}
