/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_hlavni;

import gui_okno.Vloz_osobu;
import gui_okno.Vloz_urednika1;
import gui_okno.Vlastnictvi;
import db.DBConnection;
import gui.Osoby;
import gui.Pozemky;
import gui.Stavby;
import gui.Urednici;
import gui.Vlastnici;
import gui.VsechnyOsoby;
import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;


/**
 *
 * @author strmiska
 */
public class HlavniJFrame extends javax.swing.JFrame {
    public static DBConnection dtb;
    public static HlavniJFrame hlavniOkno;
    public static Okna okna;

    
    /**
     * Creates new form HlavniJFrame
     */
    public HlavniJFrame(){
        
       initComponents();
		hlavniOkno = this;

		
		addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
				System.out.println("Ukončení spojení...");
                dtb.closeConnection();
            }
        });
   
		// nastavení parametrů okna
        this.setTitle("Metro Accidents Database");
        setSize(350,400);
        this.setLocationRelativeTo(null);  // vycentrování okna

		// otevření okna pro přihlášení
        JPanel g = new Login(this);
       
		// příprava okna pro zobrazení
		this.getContentPane().removeAll();
        this.getContentPane().setLayout(new BorderLayout());
        this.getContentPane().add(g);
        this.getContentPane().validate();
        this.getContentPane().repaint();
        setVisible(true);    
       
    }
    
    public void setOkna(Okna o){
        okna = o;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Titulek");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HlavniJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HlavniJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HlavniJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HlavniJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HlavniJFrame hlavniJFrame = null;

                    hlavniJFrame = new HlavniJFrame();

                hlavniJFrame.setLocationRelativeTo(null);
                hlavniJFrame.setVisible(true);  
            }
        });
      dtb = new DBConnection();  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
