/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_hlavni;

import gui_okno.Vloz_osobu;
import gui_okno.Vloz_urednika1;
import gui_okno.Vlastnictvi;
import db.DBConnection;
import gui.Osoby;
import gui.Pozemky;
import gui.Stavby;
import gui.Urednici;
import gui.Vlastnici;
import gui.VsechnyOsoby;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author strmiska
 */
public class Okna extends javax.swing.JPanel {
    public static DBConnection dtb;
    public static HlavniJFrame hlavniOkno;
    public static Okna okna;
    public static Vloz_osobu osoba;
    public static Vloz_urednika1 urednik;
    public static Vlastnictvi vlastnictvi;
    public VsechnyOsoby vsechnyOsoby;
    public Urednici urednici;
    public Vlastnici vlastnici;
    public Pozemky pozemky;
    public Stavby stavby;
    /**
     * Creates new form Okna
     */
    public Okna() throws SQLException, IOException {
        
        
        initComponents();
 //       hlavniOkno = this;
            okna = this;
            HlavniJFrame.hlavniOkno.setOkna(this);
            vsechnyOsoby = osoby.getVsechnyOsoby();
            urednici = osoby.getUrednici();
            vlastnici = osoby.getVlastnici();
            pozemky = nemovitosti.getPozemky();
            stavby = nemovitosti.getStavby();
            vsechnyOsoby.hlavni = hlavniOkno;
            
        osoby.inicializuj();
        nemovitosti.inicializuj();
       
    }
    public Osoby getOsoby(){
         return osoby;
    }
    
    public void zobrazOsobu(int person_pk){
        jTabbedPane1.setSelectedIndex(0);
        osoby.zobrazOkno(0);
        vsechnyOsoby.personPK = person_pk;
        vsechnyOsoby.zobrazOsobu();
    }
    public void zobrazUrednika(int person_pk){
        jTabbedPane1.setSelectedIndex(0);
        osoby.zobrazOkno(1);
        urednici.personPK = person_pk;
        urednici.zobrazUrednika();
    }
    public void zobrazVlastnika(int person_pk){
        jTabbedPane1.setSelectedIndex(0);
        osoby.zobrazOkno(2);
        vlastnici.personPK = person_pk;
        vlastnici.zobrazVlastnika();
    }
    public void zobrazPozemek(int objekt_pk){
        jTabbedPane1.setSelectedIndex(1);
        nemovitosti.zobrazOkno(0);
        pozemky.objectPK = objekt_pk;
        pozemky.zobrazPozemek();
    }
    public void zobrazStavbu(int objekt_pk){
        jTabbedPane1.setSelectedIndex(1);
        nemovitosti.zobrazOkno(1);
        stavby.objectPK = objekt_pk;
        stavby.zobrazStavbu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        osoby = new gui.Osoby();
        nemovitosti = new gui.Nemovitosti();
        jPanel4 = new javax.swing.JPanel();

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addTab("Osoby", osoby);
        jTabbedPane1.addTab("Nemovitosti", nemovitosti);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Mapa", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private gui.Nemovitosti nemovitosti;
    private gui.Osoby osoby;
    // End of variables declaration//GEN-END:variables
}
